### ISSUE TITLE
Unable to copy all from source to destination topics

### ISSUE THREAD

**Issue by arun-421** [srotya/docker-kafka-mirror-maker#2]
Hi Team,

I have tried the same step give in the description. The image is getting build and when i run the command 
docker run -it -e DESTINATION=<dest ip>:9092 -e SOURCE=<source ip>:9092 -e WHITELIST=* mirror-maker

I dont find any messages/logs in the terminal.

When I checked in the Destination kafka cluster, i couldnt find any topics copied from the source kafka cluster.

Please help

**Comment by amirwollman** [comment]
Nothing here?..
I am encountering the same exact issue. I see the group rebalancing but nothing happens afterwards.
Tried `WHITELIST=*`, `WHITELIST=.*`, with or without quotation marks and nothing..

**Comment by arun-421** [comment]
Please enter the complete command you are trying to execute. @amirwollman

**Comment by amirwollman** [comment]
Exactly as you wrote it..
docker run -it -e DESTINATION=:9092 -e SOURCE=:9092 -e WHITELIST=* mirror-maker

I noticed two things:
1. Within the container, the environmental variable named "WHITELIST" evaluates to "..docker"  (or something similar, if needed I can try that again and let you know exactly"
2. When overriding the command within the Dockerfile to `... WHITELIST=.* ...`  instead of `... WHITELIST=${WHITELIST} ...`  it works perfectly fine.

I can continue investigating this by myself for now if you require assistance with this


**Edit**
Forgot to say Thanks for the quick reply :)

**Comment by arun-421** [comment]
Hi @amirwollman try this command 

docker run -it -e DESTINATION=destination-ip:port-exposed-for-kafka -e SOURCE=source-ip:port-exposed-for-kafka -e WHITELIST= mirror-maker:latest

In my case, the port i exposed fr Kafka is 9092.
Eg:
docker run -it -e DESTINATION=10.230.129.41:9092 -e SOURCE=10.230.129.44:9092 -e WHITELIST=* mirror-maker:latest

**Comment by arun-421** [comment]
I am able to read messages. As i was trying to read it from internal port but I routed it to a node port.
